<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVj4ifrF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVj4ifrF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVj4ifrF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVj4ifrF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVj4ifrF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vj4ifrF',
    'container.build_id' => 'ccdf49a1',
    'container.build_time' => 1767280281,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVj4ifrF');
